allowBuilds:
  '@prisma/engines': true
  '@prisma/client': true
  prisma: true
  sharp: false
  unrs-resolver: false
  msw: false
  core-js: false
  '@sentry/cli': false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  kysely: 0.27.3
