import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as ConstructorParameters<typeof PrismaClient>[0]);

const AUTHOR_ID = "1ab645f2-93df-498b-851c-bce70a04d47f";

const posts = [
  {
    title: "5 Natural Ingredients That Transform Your Skin",
    slug: "5-natural-ingredients-that-transform-your-skin",
    excerpt:
      "From raw shea butter to baobab oil, Kenya's landscape is full of skin-loving ingredients. Here are five that every natural skincare routine needs.",
    category: "Skin Care",
    tags: ["ingredients", "natural", "skin care", "Kenyan beauty"],
    featuredImage: null,
    content: `
<h2>Introduction</h2>
<p>At FECHI Organics, we believe the best ingredients come straight from nature — and Africa's rich biodiversity gives us an extraordinary head start. These five ingredients sit at the heart of our formulations, and for good reason.</p>

<h2>1. Raw Shea Butter</h2>
<p>Cold-pressed shea butter is arguably the most versatile natural moisturiser on the planet. Rich in vitamins A and E, it seals moisture into the skin without clogging pores. Look for unrefined, ivory-coloured shea — the yellow variety is often processed with lye, which strips beneficial nutrients.</p>
<p><strong>Best for:</strong> Dry patches, cracked heels, post-sun recovery.</p>

<h2>2. Baobab Oil</h2>
<p>Pressed from the seeds of the iconic "tree of life," baobab oil contains a remarkable ratio of omega-3, 6 and 9 fatty acids. It absorbs almost instantly without a greasy residue, making it ideal under makeup or SPF.</p>
<p><strong>Best for:</strong> Uneven skin tone, premature ageing, sensitive skin.</p>

<h2>3. Black Soap (Ose Dudu)</h2>
<p>Traditional African black soap is made from plantain ash, palm kernel oil and shea butter. Its gentle lathering cleanses deeply without stripping the skin's acid mantle — a rare quality among cleansers.</p>
<p><strong>Best for:</strong> Acne-prone skin, hyperpigmentation, oily T-zones.</p>

<h2>4. Rosehip Seed Oil</h2>
<p>Despite its delicate name, rosehip seed oil punches above its weight in retinoid precursors (vitamin A analogues). Regular use visibly reduces post-acne marks, fine lines and sun damage over 4–8 weeks.</p>
<p><strong>Best for:</strong> Mature skin, scars, dark spots.</p>

<h2>5. Aloe Vera Gel</h2>
<p>Our Kenyan climate produces thick, polysaccharide-rich aloe that soothes inflammation on contact. Used as a toner or serum base it calms redness, tightens pores and delivers immediate hydration.</p>
<p><strong>Best for:</strong> Sunburn, reactive skin, post-shaving irritation.</p>

<h2>How to Layer These Ingredients</h2>
<p>Apply in order from lightest to heaviest: aloe gel → rosehip oil → baobab oil → shea butter (at night). This "moisture sandwich" method locks hydration in for up to 12 hours.</p>

<blockquote><p>"The most powerful beauty products grow from the ground — not a laboratory." — The FECHI Team</p></blockquote>

<p>All five ingredients feature across our core range. Check the <a href="/shop">shop</a> to find the right product for your skin type.</p>
`,
  },
  {
    title: "Building a Morning Skincare Routine for Kenya's Climate",
    slug: "morning-skincare-routine-kenya-climate",
    excerpt:
      "High altitude, equatorial sun and humidity — Kenya's unique environment demands a morning routine that protects as much as it nourishes. Here's ours.",
    category: "Skin Care",
    tags: ["routine", "morning", "SPF", "humidity", "Nairobi"],
    featuredImage: null,
    content: `
<h2>Why Kenya's Climate Is Different</h2>
<p>Nairobi sits at 1,700 m above sea level. That altitude means thinner atmosphere, which means UV radiation hits harder — about 25% more intense than at sea level. Add equatorial heat and unpredictable dry seasons and you have a combination that can dehydrate and damage skin faster than most people realise.</p>

<h2>Step 1 — Gentle Cleanse (60 seconds)</h2>
<p>Overnight your skin produces sebum and sheds dead cells. A mild foam or gel cleanser removes this without stripping. Water temperature should be lukewarm — hot water dissolves the protective lipid barrier.</p>
<p><strong>Tip:</strong> If your skin feels tight after cleansing you've over-stripped it. Switch to a cream cleanser.</p>

<h2>Step 2 — Hydrating Toner</h2>
<p>A toner rebalances skin pH (slightly acidic at 4.5–5.5) after cleansing and prepares it to absorb subsequent products. Choose alcohol-free formulas with aloe vera or niacinamide.</p>

<h2>Step 3 — Vitamin C Serum</h2>
<p>In our high-UV environment, vitamin C is non-negotiable. It neutralises free radicals generated by UV exposure before they damage collagen. Apply 3–4 drops to damp skin and let it absorb fully before the next step.</p>

<h2>Step 4 — Lightweight Moisturiser</h2>
<p>In the Nairobi heat, heavy creams pill under SPF and feel uncomfortable by mid-morning. Opt for a gel-cream or water-based moisturiser with hyaluronic acid. If you're heading to the coast or highlands, adjust weight accordingly.</p>

<h2>Step 5 — SPF 30+ (Non-Negotiable)</h2>
<p>This is the single highest-impact step you can add. Mineral SPF (zinc oxide) sits on top of the skin and reflects UV; chemical SPF absorbs and converts it to heat. For darker Kenyan skin tones, modern tinted mineral SPFs avoid the white cast problem entirely.</p>

<h2>The Full Timeline</h2>
<ul>
  <li><strong>6:30 am</strong> — Cleanse</li>
  <li><strong>6:32 am</strong> — Toner</li>
  <li><strong>6:34 am</strong> — Vitamin C serum (let sit 5 min)</li>
  <li><strong>6:39 am</strong> — Moisturiser</li>
  <li><strong>6:41 am</strong> — SPF (let sit 10 min before sun exposure)</li>
</ul>

<p>Total active time: under 15 minutes. The investment pays off in skin that ages slower and needs fewer corrective treatments later.</p>

<blockquote><p>"SPF is the one skincare product with decades of peer-reviewed evidence behind it. Everything else is maintenance — SPF is prevention."</p></blockquote>

<p>Browse our <a href="/shop?category=face-care">Face Care range</a> for climate-appropriate formulas built for Kenyan skin.</p>
`,
  },
  {
    title: "The Truth About Natural vs Synthetic Ingredients in Skincare",
    slug: "natural-vs-synthetic-skincare-ingredients",
    excerpt:
      "Not everything natural is safe, and not everything synthetic is harmful. We break down the nuance so you can read labels with confidence.",
    category: "Education",
    tags: ["ingredients", "education", "clean beauty", "label reading"],
    featuredImage: null,
    content: `
<h2>The "Natural = Good" Assumption</h2>
<p>Walk into any pharmacy and you'll see "100% natural" stamped on products sitting next to "dermatologist-tested" ones at twice the price. The implication is clear: natural is superior. But is it?</p>
<p>Poison ivy is natural. So is arsenic. Meanwhile, some of the most effective and well-studied skincare ingredients — niacinamide, hyaluronic acid, retinol — are synthesised in labs because that's the only way to produce them at the purity and scale skincare requires.</p>

<h2>What "Natural" Actually Means on a Label</h2>
<p>There is no regulated definition of "natural" in the cosmetics industry in Kenya or most other countries. A product can legally call itself natural while containing just 1% botanical extract alongside a full roster of synthetics. This is not fraud per se, but it is marketing.</p>

<p>What to look for instead:</p>
<ul>
  <li><strong>COSMOS or Ecocert certification</strong> — third-party verification with strict sourcing standards.</li>
  <li><strong>Full ingredient list (INCI)</strong> — required by law in the EU; increasingly common on quality Kenyan brands.</li>
  <li><strong>Named sources</strong> — "shea butter (Vitellaria paradoxa)" is more trustworthy than just "plant extract."</li>
</ul>

<h2>Synthetic Ingredients Worth Embracing</h2>
<p><strong>Niacinamide (vitamin B3)</strong> — reduces pores, controls sebum, fades hyperpigmentation. Synthetically produced because the natural form degrades too quickly to be useful in formulations.</p>
<p><strong>Hyaluronic acid</strong> — a humectant that holds 1,000× its weight in water. Fermented from bacteria, not extracted from animals. Vegan and highly effective.</p>
<p><strong>Retinol (vitamin A)</strong> — the gold standard for anti-ageing. Derived through synthesis because the plant precursor (beta-carotene) is too unstable and poorly converted by most skin types.</p>

<h2>Natural Ingredients That Deserve Caution</h2>
<p><strong>Essential oils</strong> — fragrant, popular, but among the top causes of contact dermatitis. Lemon, bergamot and cinnamon oil are phototoxic (react with sunlight to cause burns).</p>
<p><strong>Witch hazel</strong> — the alcohol-heavy version disrupts the skin barrier; look for distillate versions without alcohol.</p>
<p><strong>Citrus extracts</strong> — often used to brighten but are highly photosensitising. Only use in night products.</p>

<h2>Our Approach at FECHI</h2>
<p>We formulate with a simple principle: <em>evidence first, source second</em>. If the best available form of an ingredient happens to be naturally derived, we use it. If a synthetic version performs better or is safer, we use that. We are transparent about every ingredient on every label.</p>

<p>Have questions about a specific ingredient? Drop us a message via the <a href="/contact">contact page</a>.</p>
`,
  },
  {
    title: "How to Care for Your Hair in the Kenyan Dry Season",
    slug: "hair-care-kenyan-dry-season",
    excerpt:
      "January and July–August bring dry, dusty winds that wreak havoc on natural hair. These protective strategies will keep your strands healthy all season.",
    category: "Hair Care",
    tags: ["hair care", "dry season", "natural hair", "protective styles"],
    featuredImage: null,
    content: `
<h2>Understanding the Kenyan Dry Season's Effect on Hair</h2>
<p>Kenya experiences two distinct dry seasons: January to mid-March, and July to October. During these periods, the humidity in Nairobi can drop below 30% — a level at which unprotected natural hair begins to lose moisture rapidly, leading to breakage and dullness.</p>
<p>Dusty harmattan-influenced winds also deposit fine particles on the scalp that clog follicles and dull the hair shaft. The result? Hair that looks and feels like it's perpetually thirsty.</p>

<h2>The L.O.C. Method for Moisture Retention</h2>
<p>This sequencing method — Liquid, Oil, Cream — is designed specifically for natural African hair textures and works exceptionally well in dry conditions.</p>
<ol>
  <li><strong>Liquid</strong> — water or an aloe vera-based leave-in. Water is the actual moisturiser; everything else seals it in.</li>
  <li><strong>Oil</strong> — a light penetrating oil like baobab or jojoba seals the hair cuticle over the water layer.</li>
  <li><strong>Cream</strong> — a heavier cream or butter (shea, mango butter) locks everything in as a final barrier against moisture evaporation.</li>
</ol>
<p>Apply to small sections on damp (not soaking wet) hair for best results.</p>

<h2>Protective Styles for the Season</h2>
<p>Keeping the ends of your hair tucked away reduces the friction and environmental exposure that cause split ends. Good dry-season protective styles include:</p>
<ul>
  <li>Braids with a natural leave-in underneath (not tight — tension damage is real)</li>
  <li>Bantu knots worn overnight as a set, then released</li>
  <li>Wigs with a satin-lined cap to protect your edges</li>
</ul>
<p><strong>Important:</strong> Protective styles still need scalp care. Apply a diluted rosemary oil mixture to your scalp every 5–7 days and massage for 3 minutes to maintain circulation and prevent build-up.</p>

<h2>Deep Conditioning Frequency</h2>
<p>During the dry season, increase deep conditioning from once a month to once a week. Apply a rich conditioner to damp, detangled hair and cover with a plastic cap. Heat from a hooded dryer or warm towel opens the cuticle and allows the conditioner to penetrate the cortex — not just coat the surface.</p>
<p>Leave on for 20–30 minutes, then rinse with cool water to close the cuticle and lock in shine.</p>

<h2>Scalp Health First</h2>
<p>Moisturised scalp = moisturised hair. During dry season, switch from clarifying shampoo to a co-wash or gentle sulphate-free shampoo. Wash weekly rather than bi-weekly to remove dust build-up, but compensate with a heavier conditioner to offset any moisture loss from washing.</p>

<blockquote><p>"Your hair's health begins at the scalp. Treat the skin on your head with the same care you give your face."</p></blockquote>

<p>Explore our <a href="/shop?category=hair-care">Hair Care range</a> for products formulated with baobab, castor oil and rosemary — three of the most research-backed ingredients for Kenyan hair types.</p>
`,
  },
  {
    title: "Why We Source Locally: Fechi's Ingredient Supply Chain",
    slug: "fechi-local-ingredient-sourcing",
    excerpt:
      "From shea cooperatives in West Africa to baobab farmers in the Rift Valley — here's how FECHI Organics sources its key ingredients and why it matters.",
    category: "Our Story",
    tags: ["sourcing", "sustainability", "Kenya", "brand story", "farmers"],
    featuredImage: null,
    content: `
<h2>Why Sourcing Matters More Than the Label</h2>
<p>Two bottles of shea butter sitting on a shelf can look identical and perform very differently depending on how the shea was harvested, processed and stored. One might come from a cooperative of women in Northern Ghana who hand-press using traditional methods and earn a fair wage. The other might be bleached, deodorised and shipped in bulk at minimum cost. Only one of them is doing what the label promises.</p>
<p>At FECHI, our supply chain starts with a question: where does this actually come from?</p>

<h2>Baobab Oil — The Rift Valley</h2>
<p>Kenya's Rift Valley is home to ancient baobab trees, some over 1,000 years old. We source baobab seed oil from small-scale collectors in this region who harvest fallen seeds seasonally — a practice that does not harm the trees and provides supplementary income to pastoral families.</p>
<p>The oil is cold-pressed within 48 hours of collection to preserve its fatty acid profile, then tested for peroxide value (a measure of freshness) before we accept a batch.</p>

<h2>Shea Butter — West African Women's Cooperatives</h2>
<p>No baobab tree produces shea — those come from the shea belt stretching from Senegal to Uganda. We partner with women-led cooperatives in Ghana that use traditional A-grade extraction methods: boiling, churning and pressing by hand rather than solvent extraction.</p>
<p>This is slower and more expensive. It is also the only way to get unrefined shea with its full complement of vitamins A, E and F intact.</p>

<h2>Aloe Vera — Central Kenya</h2>
<p>We source aloe vera gel from certified organic farms in the Mount Kenya region, where the volcanic soil and moderate rainfall produce plants with exceptionally high polysaccharide concentrations. The gel is cold-processed and tested for acemannan content — the active compound responsible for aloe's anti-inflammatory and wound-healing properties.</p>

<h2>Essential Oils — Kenya and East Africa</h2>
<p>Lavender from Kikuyu, rosemary from the Aberdares, geranium from Limuru. East Africa's highland elevations and rich volcanic soils produce essential oils with chemical profiles distinct from — and often superior to — those grown in Europe. We work directly with small-scale distillers, not commodity brokers, to ensure traceability from plant to bottle.</p>

<h2>Our Commitment Going Forward</h2>
<p>By 2027, our goal is for 80% of our key actives to be sourced within East Africa. This supports local agricultural economies, reduces our logistics carbon footprint, and lets us verify quality at source rather than trusting third-party certificates.</p>
<p>Every time you buy a FECHI product, part of what you're paying for is a supply chain that was built to benefit the people and land that make it possible.</p>

<blockquote><p>"Local sourcing isn't a marketing decision. It's a quality decision." — Jefferson Kimotho, Founder</p></blockquote>

<p>Learn more about who we are on our <a href="/about">About page</a>, or explore our <a href="/shop">full product range</a>.</p>
`,
  },
  {
    title: "Understanding Hyperpigmentation: Causes, Types and Natural Fixes",
    slug: "understanding-hyperpigmentation-natural-fixes",
    excerpt:
      "Dark spots, uneven tone and post-acne marks affect over 65% of people with darker skin tones. Here's what's actually happening in your skin — and what works.",
    category: "Education",
    tags: ["hyperpigmentation", "dark spots", "melanin", "skin tone", "education"],
    featuredImage: null,
    content: `
<h2>What Is Hyperpigmentation?</h2>
<p>Hyperpigmentation is the overproduction of melanin — the pigment that gives skin, hair and eyes their colour — in specific areas of the skin. It presents as patches or spots that are darker than the surrounding skin. It is not harmful, but it is extremely common, and for many people it affects confidence profoundly.</p>

<h2>The Three Main Types</h2>

<h3>1. Post-Inflammatory Hyperpigmentation (PIH)</h3>
<p>The most common type in darker skin tones. It appears after an injury to the skin — acne, a cut, an ingrown hair, even aggressive exfoliation. The melanocytes (melanin-producing cells) overreact to inflammation and produce excess pigment at the site. PIH is most pronounced in Fitzpatrick skin types IV–VI (medium brown to deep dark skin) because those skin types have more active melanocytes to begin with.</p>

<h3>2. Melasma</h3>
<p>Triggered by hormones — most commonly oestrogen and progesterone — and worsened dramatically by sun exposure. It is extremely common during pregnancy (sometimes called the "mask of pregnancy") and in women on hormonal contraception. Melasma appears symmetrically, typically on the cheeks, forehead and upper lip.</p>
<p><strong>Key point:</strong> Melasma cannot be permanently resolved with topicals alone if the hormonal trigger remains active. SPF is essential and often more effective than any brightening serum.</p>

<h3>3. Sun Spots (Solar Lentigines)</h3>
<p>Flat, well-defined spots caused by cumulative UV exposure. They tend to appear in areas of repeated sun exposure — forearms, hands, cheeks — and become more pronounced with age. They are directly preventable with consistent SPF use.</p>

<h2>Ingredients That Actually Work</h2>

<p><strong>Vitamin C (ascorbic acid)</strong> — Inhibits the enzyme tyrosinase, which is required for melanin production. Also provides antioxidant protection against future UV damage. Use a stable, pH-appropriate form (around 3.5) for maximum efficacy.</p>

<p><strong>Niacinamide</strong> — Does not inhibit melanin production, but prevents its transfer from melanocytes to keratinocytes (surface skin cells). This is the step that actually causes visible darkening, making niacinamide unusually effective for PIH. Minimal irritation, suitable for sensitive skin.</p>

<p><strong>Alpha Arbutin</strong> — A glycosylated form of hydroquinone that inhibits tyrosinase without the side effects associated with hydroquinone. Gentler and stable in formulations up to 2%.</p>

<p><strong>Azelaic Acid</strong> — Anti-inflammatory, anti-bacterial and anti-pigmentation in one ingredient. Particularly effective for PIH because it addresses the underlying inflammation alongside the pigmentation. Available OTC up to 10%; prescription strength is 15–20%.</p>

<p><strong>Retinol</strong> — Accelerates cell turnover, bringing fresh, unpigmented cells to the surface faster. Works best in combination with a brightening agent rather than alone.</p>

<h2>The Non-Negotiable: SPF</h2>
<p>Every brightening ingredient in the world is undermined by unprotected sun exposure. UV radiation directly stimulates melanin production. Without SPF, you are filling a bucket with a hole in the bottom.</p>
<p>SPF 30 minimum, broad-spectrum, every morning — including on cloudy days and indoors if you work near a window.</p>

<h2>Realistic Timelines</h2>
<ul>
  <li><strong>6 weeks</strong> — first visible changes with consistent use of actives + SPF</li>
  <li><strong>3 months</strong> — significant reduction in PIH and mild sun spots</li>
  <li><strong>6–12 months</strong> — melasma management (not elimination — management)</li>
</ul>
<p>Hyperpigmentation responds to consistency, not intensity. Steady, gentle treatment over months outperforms aggressive treatment that causes inflammation and new PIH.</p>

<p>Our brightening range combines vitamin C, niacinamide and alpha arbutin in a formulation designed for African skin tones. <a href="/shop?category=face-care">Browse the Face Care range</a> to find your starting point.</p>
`,
  },
];

async function main() {
  console.log(`\nSeeding ${posts.length} blog posts...\n`);

  for (const post of posts) {
    const result = await prisma.blogPost.upsert({
      where: { slug: post.slug },
      update: {
        title: post.title,
        excerpt: post.excerpt,
        content: post.content.trim(),
        category: post.category,
        tags: post.tags,
        status: "PUBLISHED",
        publishedAt: new Date(),
        authorId: AUTHOR_ID,
      },
      create: {
        title: post.title,
        slug: post.slug,
        excerpt: post.excerpt,
        content: post.content.trim(),
        category: post.category,
        tags: post.tags,
        status: "PUBLISHED",
        publishedAt: new Date(),
        authorId: AUTHOR_ID,
        featuredImage: post.featuredImage,
      },
    });
    console.log(`  ✓ "${result.title}" [${result.id}]`);
  }

  console.log("\nDone.\n");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
