/**
 * Lets a referral code work as a coupon at checkout.
 *
 * A customer's referral code (REF-XXXXXX) is not a `promotion` row — creating
 * one per customer would flood that table — so resolvePromo() rejects it. This
 * fills that gap: an unrecognised code is checked against referral codes before
 * the checkout gives up on it.
 *
 * First-time customers only, and never your own code. The referral link itself
 * is recorded later, at payment success, by the award-points worker — a code
 * typed into an abandoned checkout must not burn anybody's referral slot.
 */

// Reaches the database. Importing this from a client component pulls the
// Postgres driver into the browser bundle — this makes that fail loudly at
// the import instead of as a wall of pg module-not-found errors.
import "server-only";

import { db } from "@/lib/db";
import { REFERRAL_DISCOUNT_PERCENT } from "@/lib/points/rules";

// Re-exported for existing server call sites. Client components must import it
// from @/lib/points/rules directly — this module reaches the database, so
// importing it from the browser breaks the build.
export { REFERRAL_DISCOUNT_PERCENT };

/** Prefix generated by makeCode("REF") in lib/points/ledger.ts. */
const REFERRAL_PREFIX = "REF-";

export function looksLikeReferralCode(code: string): boolean {
  return code.trim().toUpperCase().startsWith(REFERRAL_PREFIX);
}

export type ReferralDiscount = {
  code: string;
  referrerUserId: string;
  discountCents: number;
};

export async function resolveReferralDiscount(args: {
  code: string;
  subtotalCents: number;
  userId?: string | null;
  /**
   * Order being paid for right now, excluded from the "have you ordered
   * before?" check — otherwise the very order the code is being used on
   * disqualifies it.
   */
  ignoreOrderId?: string;
}): Promise<ReferralDiscount | null> {
  const code = args.code.trim().toUpperCase();
  if (!looksLikeReferralCode(code) || !args.userId) return null;

  const owner = await db.loyaltyPoints.findUnique({
    where: { referralCode: code },
    select: { userId: true },
  });
  if (!owner || owner.userId === args.userId) return null;

  // First-time customers only.
  const priorPaidOrders = await db.order.count({
    where: {
      userId: args.userId,
      paymentStatus: "PAID",
      ...(args.ignoreOrderId ? { id: { not: args.ignoreOrderId } } : {}),
    },
  });
  if (priorPaidOrders > 0) return null;

  return {
    code,
    referrerUserId: owner.userId,
    discountCents: Math.round((args.subtotalCents * REFERRAL_DISCOUNT_PERCENT) / 100),
  };
}
